#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += ccu.o

obj-$(CONFIG_PLATFORM_A64) += ccu-a64.o
obj-$(CONFIG_PLATFORM_A64) += r_prcm-a64.o
