#
# Copyright © 2017-2019 The Crust Firmware Authors.
# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
#

obj-y += clock/
obj-y += css/
obj-y += gpio/
obj-y += irqchip/
obj-y += msgbox/
obj-y += pmic/
obj-y += rsb/
obj-y += watchdog/
